version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    restart: unless-stopped
    env_file: ./api/.env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017/helpdesk
    ports: ["8080:8080"]
    depends_on: [mongo]

  client:
    build: ./client
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8080
    ports: ["5173:5173"]
    depends_on: [api]

volumes:
  mongo-data:
